spring:
  datasource:
    url: jdbc:sqlite:race.db
    driver-class-name: org.sqlite.JDBC
    sql-script-encoding: UTF-8
logging:
  file: log/log.log
  level: 
    root: info
nk:
  # analyze: '20181229000136'
  analyze: ''
  task:
    createMatcher: true
    calculation: true
    readAndCalc: true
  calculation-debug-mode: false
  caluculation-logging-span: 10
  gridSize: 8
